name       : gnome-pomodoro
version    : 0.12.3
release    : 2
source     :
    - https://github.com/codito/gnome-pomodoro/archive/0.12.3.tar.gz : 3d514581852676794ca58e1cfb11a426214e625cb9769ae5b6ad41569a9db778
license    : GPL-3.0
component  : office
summary    : A Pomodoro timer for GNOME
description: |
    GNOME Pomodoro is a small application that helps managing time according to Pomodoro Technique. It intends to improve productivity and focus by taking short breaks
builddeps  :
    - pkgconfig(gnome-desktop-3.0)
    - pkgconfig(gsettings-desktop-schemas)
    - pkgconfig(gstreamer-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libcanberra)
    - pkgconfig(libpeas-1.0)
    - gnome-common
    - vala
setup      : |
    %autogen --disable-static
build      : |
    %make
install    : |
    %make_install
