name       : gnome-pomodoro
version    : 0.13.1
release    : 4
source     :
    - https://github.com/codito/gnome-pomodoro/archive/0.13.1.tar.gz : 52b27f2cef1e06eb5ab51a1fb06ac29c88bbfd825d809fc5c81d482897123318
license    : GPL-3.0
component  : office
summary    : A Pomodoro timer for GNOME
description: |
    GNOME Pomodoro is a small application that helps managing time according to Pomodoro Technique. It intends to improve productivity and focus by taking short breaks
builddeps  :
    - pkgconfig(appstream-glib)
    - pkgconfig(gnome-desktop-3.0)
    - pkgconfig(gsettings-desktop-schemas)
    - pkgconfig(gstreamer-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libcanberra)
    - pkgconfig(libpeas-1.0)
    - gnome-common
    - vala
setup      : |
    %autogen --disable-static
build      : |
    %make
install    : |
    %make_install
