name       : gnome-pomodoro
version    : 0.23.1
release    : 16
source     :
    - https://github.com/gnome-pomodoro/gnome-pomodoro/archive/refs/tags/0.23.1.tar.gz : b552255d73a3ab531f8e503ededfa5a3949b1e4359f393980a8cbb5451dec081
license    : GPL-3.0-or-later
component  : office
summary    : A Pomodoro timer for GNOME
description: |
    GNOME Pomodoro is a small application that helps managing time according to Pomodoro Technique. It intends to improve productivity and focus by taking short breaks
builddeps  :
    - pkgconfig(appstream-glib)
    - pkgconfig(gnome-desktop-3.0)
    - pkgconfig(gom-1.0)
    - pkgconfig(gsettings-desktop-schemas)
    - pkgconfig(gstreamer-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libcanberra)
    - pkgconfig(libpeas-1.0)
    - pkgconfig(sqlite3)
    - gnome-common
    - vala
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
