name       : gnome-pomodoro
version    : 0.19.1
release    : 13
source     :
    - https://github.com/gnome-pomodoro/gnome-pomodoro/archive/refs/tags/0.19.1.tar.gz : b14169038c72da04d2ed748cd53976a4ea570ca6b51d61da52592cf8302bb3db
license    : GPL-3.0-or-later
component  : office
summary    : A Pomodoro timer for GNOME
description: |
    GNOME Pomodoro is a small application that helps managing time according to Pomodoro Technique. It intends to improve productivity and focus by taking short breaks
builddeps  :
    - pkgconfig(appstream-glib)
    - pkgconfig(gnome-desktop-3.0)
    - pkgconfig(gom-1.0)
    - pkgconfig(gsettings-desktop-schemas)
    - pkgconfig(gstreamer-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libcanberra)
    - pkgconfig(libpeas-1.0)
    - pkgconfig(sqlite3)
    - gnome-common
    - vala
setup      : |
    %autogen --disable-static
build      : |
    %make
install    : |
    %make_install
